from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any


@dataclass
class ModelCardWriter:
    output_path: Path

    def write(
        self,
        metrics: dict[str, Any],
        selected_model: str,
        feature_names: list[str],
        rows: int,
    ) -> Path:
        content = f"""# Regulated Risk ML Baseline Model Card

## Intended Use

Advisory human-review triage for a simulated regulated decision-support workflow. The model helps reviewers inspect feature engineering, metrics, calibration, and model governance artifacts.

## Out-Of-Scope Use

- Automated credit, eligibility, procurement, legal, aid allocation, or customer decisions.
- Production compliance certification.
- Real CRIF, PwC, UNDP, CINECA, IT4LIA, BI-REX, employer, customer, or public-sector deployment.

## Data

- Rows: {rows}
- Source: synthetic dataset generated by `ml-baseline/src/regulated_risk_ml/data.py`.
- Disclaimer: simulated data only, with synthetic labels.

## Selected Model

`{selected_model}`

## Features

{chr(10).join(f"- `{feature}`" for feature in feature_names)}

## Metrics

- ROC-AUC: `{metrics['roc_auc']}`
- PR-AUC: `{metrics['pr_auc']}`
- F1: `{metrics['f1']}`
- Precision: `{metrics['precision']}`
- Recall: `{metrics['recall']}`
- Brier score: `{metrics['brier_score']}`

## Fairness, Ethics, And Human Review

This baseline is not a fairness-certified or legally reviewed model. It is a portfolio simulation. Any real regulated use would require legal review, bias testing, data protection assessment, monitoring, stakeholder governance, and human accountability.

## Deployment Status

Local simulation only. `model.joblib` is a reviewer artifact when generated; it is not a production model registry entry.
"""
        self.output_path.parent.mkdir(parents=True, exist_ok=True)
        self.output_path.write_text(content, encoding="utf-8")
        return self.output_path
